@startuml Position Operations
actor Alice

collections USDT_Alice
collections USDT_Vault

database    Vault

collections ReferralNFT

collections Position_Alice

participant AMM

group "Increase position"

Alice -> USDT_Alice : transfer + increase_position payload
USDT_Alice -> USDT_Vault : internal_transfer
USDT_Vault -> Vault : transfer_notification (increase_position)
USDT_Vault -> Alice : excess
Vault -> Position_Alice : provide_position (increase_position)
Position_Alice -> AMM : take_position (increase_position)
AMM -> Position_Alice : update_position
Position_Alice -> Alice : excess
AMM -> Vault : trade_notification
Vault -> Alice : excess

end

group "Increase position (with referral)"

Alice -> USDT_Alice : transfer + increase_position payload
USDT_Alice -> USDT_Vault : internal_transfer
USDT_Vault -> Vault : transfer_notification (increase_position)
USDT_Vault -> Alice : excess
Vault -> Position_Alice : provide_position (increase_position)
Position_Alice -> AMM : take_position (increase_position)
AMM -> Position_Alice : update_position
Position_Alice -> Alice : excess
AMM -> Vault : trade_notification
Vault -> ReferralNFT : add_referral_amounmt
ReferralNFT -> Alice : excess

end


group "Increase position (initiating Position Manager, no referral)"

Alice -> USDT_Alice : transfer + increase_position payload
USDT_Alice -> USDT_Vault : internal_transfer
USDT_Vault -> Vault : transfer_notification (increase_position)
USDT_Vault -> Alice : excess
Vault -> Position_Alice : init_position_position (increase_position)
Position_Alice -> AMM : take_position (increase_position)
AMM -> Position_Alice : update_position
Position_Alice -> Alice : excess
AMM -> Vault : trade_notification
Vault -> Alice : excess

end

group "Increase position (initiating Position Manager, with referral)"

Alice -> USDT_Alice : transfer + increase_position payload
USDT_Alice -> USDT_Vault : internal_transfer
USDT_Vault -> Vault : transfer_notification (increase_position)
USDT_Vault -> Alice : excess
Vault -> Position_Alice : init_position_position (increase_position)
Position_Alice -> ReferralNFT : provide_referral_fees
ReferralNFT -> Position_Alice : take_referral_fees
Position_Alice -> AMM : take_position (increase_position)
AMM -> Position_Alice : update_position
Position_Alice -> Alice : excess
AMM -> Vault : trade_notification
Vault -> ReferralNFT : add_referral_amounmt
ReferralNFT -> Alice : excess

end

group "Increase position with stop-loss/take-profit"

Alice -> USDT_Alice : transfer + increase_position payload
USDT_Alice -> USDT_Vault : internal_transfer
USDT_Vault -> Vault : transfer_notification (increase_position)
USDT_Vault -> Alice : excess
Vault -> Position_Alice : provide_position (increase_position)
Position_Alice -> AMM : take_position (increase_position)
AMM -> Position_Alice : update_position_with_stop_loss
Position_Alice -> Alice : excess
AMM -> Vault : trade_notification
Vault -> Alice : excess

end
